local _, ns = ...

function ns.CreateSettings(app)
    local db = app.db
    local panel = CreateFrame("Frame", "PartyTargetWatchSettings", UIParent, "BackdropTemplate")
    panel:SetSize(540, 650)
    panel:SetPoint("CENTER")
    panel:SetFrameStrata("DIALOG")
    panel:SetClampedToScreen(true)
    panel:EnableMouse(true)
    panel:SetMovable(true)
    panel:RegisterForDrag("LeftButton")
    panel:SetScript("OnDragStart", panel.StartMoving)
    panel:SetScript("OnDragStop", panel.StopMovingOrSizing)
    panel:SetBackdrop({ bgFile = "Interface\\Buttons\\WHITE8X8", edgeFile = "Interface\\Buttons\\WHITE8X8", edgeSize = 1 })
    panel:SetBackdropColor(0.035, 0.055, 0.075, 0.98)
    panel:SetBackdropBorderColor(0.25, 0.7, 0.65, 1)
    UISpecialFrames[#UISpecialFrames + 1] = "PartyTargetWatchSettings"
    local function Text(text, x, y, font)
        local label = app.NewText(panel, font or "GameFontHighlight")
        label:SetPoint("TOPLEFT", x, y)
        label:SetText(text)
        return label
    end
    Text("队友目标 · 设置", 20, -18, "GameFontNormalLarge")
    local close = CreateFrame("Button", nil, panel, "UIPanelCloseButton")
    close:SetPoint("TOPRIGHT", -4, -4)
    close:SetScript("OnClick", function() panel:Hide() end)
    local function Button(text, x, y, width, callback)
        local button = CreateFrame("Button", nil, panel, "UIPanelButtonTemplate")
        button:SetSize(width, 25)
        button:SetPoint("TOPLEFT", x, y)
        button:SetText(text)
        button:SetScript("OnClick", callback)
        return button
    end
    local checks = {}
    local function Check(key, text, x, y, changed)
        local check = CreateFrame("CheckButton", nil, panel, "UICheckButtonTemplate")
        check:SetSize(26, 26)
        check:SetPoint("TOPLEFT", x, y)
        check.Text = check.Text or app.NewText(check, "GameFontHighlight")
        check.Text:ClearAllPoints()
        check.Text:SetPoint("LEFT", check, "RIGHT", 2, 0)
        check.Text:SetText(text)
        check:SetScript("OnClick", function(self)
            local value = not not self:GetChecked()
            -- Stateful setters must observe the previous saved value.
            if changed then changed(value) else db[key] = value end
            app.RebuildRoster()
        end)
        checks[key] = check
    end
    Text("显示场景", 22, -54, "GameFontNormal")
    Check("showWorld", "野外", 20, -78)
    Check("showResting", "主城/旅店（休息区）", 258, -78)
    Check("showDungeon", "地下城（含大秘境）", 20, -108)
    Check("showRaid", "团队副本", 258, -108)
    Check("showScenario", "场景战役", 20, -138)
    Check("showBattleground", "战场", 258, -138)
    Check("showArena", "竞技场", 20, -168)
    local scene = Text("", 258, -175, "GameFontDisableSmall")
    scene:SetWidth(260)
    Text("副本类型优先；示例预览忽略场景筛选。", 22, -207, "GameFontDisableSmall")
    Text("焦点与通报", 22, -238, "GameFontNormal")
    Check("showFocus", "显示焦点 / 通报列", 20, -260)
    Check("acceptFocusCalls", "接收队友的焦点通报", 20, -290, ns.Communication.SetAcceptCalls)
    Button("接收格式…", 382, -290, 136, app.ShowFormats)
    Check("shareFocus", "插件间焦点同步（可选）", 20, -320, ns.Communication.SetEnabled)
    local info = Text("聊天通报：开启前两项并配置接收格式；队友无需安装本插件。\n黄色名称 / 标记来自最近一次通报；换焦点后需再次通报。\n记录保留 5 分钟；队伍里说“取消打断”可清除本人记录。\n插件同步：双方安装并开启，仅在游戏允许时生效。", 22, -354, "GameFontDisableSmall")
    info:SetWidth(496)
    info:SetWordWrap(true)
    info:SetHeight(56)
    local scaleLabel = Text("", 22, -418)
    local scale = CreateFrame("Slider", "PartyTargetWatchScaleSlider", panel)
    scale:SetPoint("TOPLEFT", 24, -445)
    scale:SetSize(226, 16)
    scale:SetOrientation("HORIZONTAL")
    scale:EnableMouse(true)
    scale:SetThumbTexture("Interface\\Buttons\\UI-SliderBar-Button-Horizontal")
    scale:GetThumbTexture():SetSize(24, 24)
    local track = scale:CreateTexture(nil, "BACKGROUND")
    track:SetPoint("LEFT", 0, 0)
    track:SetPoint("RIGHT", 0, 0)
    track:SetHeight(4)
    track:SetColorTexture(0.2, 0.4, 0.42, 1)
    scale:SetMinMaxValues(0.6, 2)
    scale:SetValueStep(0.05)
    scale:SetObeyStepOnDrag(true)
    Text("60%", 22, -467, "GameFontDisableSmall")
    Text("200%", 221, -467, "GameFontDisableSmall")
    local backgroundLabel = Text("", 284, -418)
    local background = CreateFrame("Slider", "PartyTargetWatchBackgroundAlphaSlider", panel)
    background:SetPoint("TOPLEFT", 286, -445)
    background:SetSize(228, 16)
    background:SetOrientation("HORIZONTAL")
    background:EnableMouse(true)
    background:SetThumbTexture("Interface\\Buttons\\UI-SliderBar-Button-Horizontal")
    background:GetThumbTexture():SetSize(24, 24)
    local backgroundTrack = background:CreateTexture(nil, "BACKGROUND")
    backgroundTrack:SetPoint("LEFT", 0, 0)
    backgroundTrack:SetPoint("RIGHT", 0, 0)
    backgroundTrack:SetHeight(4)
    backgroundTrack:SetColorTexture(0.2, 0.4, 0.42, 1)
    background:SetMinMaxValues(0, 1)
    background:SetValueStep(0.01)
    background:SetObeyStepOnDrag(true)
    Text("全透明", 284, -467, "GameFontDisableSmall")
    Text("不透明", 477, -467, "GameFontDisableSmall")
    Text("位置偏移 X / Y", 22, -494)
    local function Input(x)
        local box = CreateFrame("EditBox", nil, panel, "InputBoxTemplate")
        box:SetSize(75, 24)
        box:SetPoint("TOPLEFT", x, -490)
        box:SetAutoFocus(false)
        box:SetMaxLetters(9)
        box:SetScript("OnEscapePressed", box.ClearFocus)
        return box
    end
    local xInput, yInput = Input(145), Input(235)
    local status = Text("正值向右 / 向上；也可以解锁后拖动窗口标题。", 22, -526, "GameFontDisableSmall")
    status:SetWidth(500)
    local function ApplyPosition()
        local x, y = tonumber(xInput:GetText()), tonumber(yInput:GetText())
        if not app.ValidNumber(x, -10000, 10000) or not app.ValidNumber(y, -10000, 10000) then
            status:SetText("请输入 -10000 到 10000 之间的位置数值。") return
        end
        db.x, db.y = x, y
        app.RestorePosition()
        xInput:ClearFocus() yInput:ClearFocus()
        status:SetText("位置已保存。")
    end
    Button("应用位置", 333, -490, 92, ApplyPosition)
    xInput:SetScript("OnEnterPressed", ApplyPosition)
    yInput:SetScript("OnEnterPressed", ApplyPosition)
    local visibility = Button("", 22, -556, 154, function() db.hidden = not db.hidden app.RebuildRoster() end)
    local lock = Button("", 193, -556, 154, function()
        app.SavePosition() db.locked = not db.locked app.RebuildRoster()
    end)
    local test = Button("", 364, -556, 154, app.TogglePreview)
    Button("窗口居中", 22, -605, 154, function()
        db.point, db.relativePoint, db.x, db.y = "CENTER", "CENTER", 0, 0
        db.hidden = false app.RestorePosition() app.RebuildRoster()
    end)
    Button("恢复默认", 193, -605, 154, app.Reset)
    Button("完成", 364, -605, 154, function() panel:Hide() end)
    local syncing = false
    panel.Sync = function()
        if not panel:IsShown() then return end
        syncing = true
        for key, check in pairs(checks) do check:SetChecked(db[key]) end
        scale:SetValue(db.scale)
        background:SetValue(db.backgroundAlpha)
        scaleLabel:SetText("整体大小：" .. math.floor(db.scale * 100 + 0.5) .. "%")
        backgroundLabel:SetText("背景不透明度：" .. math.floor(db.backgroundAlpha * 100 + 0.5) .. "%")
        xInput:SetText(string.format("%.1f", db.x))
        yInput:SetText(string.format("%.1f", db.y))
        scene:SetText("当前：" .. (app.sceneLabel or "野外"))
        visibility:SetText(db.hidden and "显示监控窗口" or "隐藏监控窗口")
        lock:SetText(db.locked and "解锁位置" or "锁定位置")
        test:SetText(app.preview and "结束示例预览" or "显示示例预览")
        syncing = false
    end
    scale:SetScript("OnValueChanged", function(_, value)
        if syncing or not app.ValidNumber(value, 0.6, 2) then return end
        db.scale = math.floor(value * 100 + 0.5) / 100
        app.RestorePosition()
        scaleLabel:SetText("整体大小：" .. math.floor(db.scale * 100 + 0.5) .. "%")
    end)
    background:SetScript("OnValueChanged", function(_, value)
        if syncing or not app.ValidNumber(value, 0, 1) then return end
        db.backgroundAlpha = math.floor(value * 100 + 0.5) / 100
        app.ApplyAppearance()
        backgroundLabel:SetText("背景不透明度：" .. math.floor(db.backgroundAlpha * 100 + 0.5) .. "%")
    end)
    panel:SetScript("OnShow", panel.Sync)
    return panel
end

function ns.CreateFormatSettings(app)
    local panel = CreateFrame("Frame", "PartyTargetWatchFormatSettings", UIParent, "BackdropTemplate")
    panel:Hide()
    panel:SetSize(620, 575)
    panel:SetPoint("CENTER")
    panel:SetFrameStrata("DIALOG")
    panel:SetFrameLevel(10)
    panel:SetClampedToScreen(true)
    panel:EnableMouse(true)
    panel:SetMovable(true)
    panel:SetBackdrop({ bgFile = "Interface\\Buttons\\WHITE8X8", edgeFile = "Interface\\Buttons\\WHITE8X8", edgeSize = 1 })
    panel:SetBackdropColor(0.035, 0.055, 0.075, 0.98)
    panel:SetBackdropBorderColor(0.25, 0.7, 0.65, 1)
    UISpecialFrames[#UISpecialFrames + 1] = "PartyTargetWatchFormatSettings"
    local function Text(text, x, y, font)
        local label = app.NewText(panel, font or "GameFontHighlight")
        label:SetPoint("TOPLEFT", x, y)
        label:SetText(text)
        return label
    end
    local handle = CreateFrame("Frame", nil, panel)
    handle:SetPoint("TOPLEFT", 0, 0)
    handle:SetPoint("TOPRIGHT", -32, 0)
    handle:SetHeight(40)
    handle:EnableMouse(true)
    handle:RegisterForDrag("LeftButton")
    handle:SetScript("OnDragStart", function() panel:StartMoving() end)
    handle:SetScript("OnDragStop", function() panel:StopMovingOrSizing() end)
    Text("聊天通报接收格式", 20, -18, "GameFontNormalLarge")
    local close = CreateFrame("Button", nil, panel, "UIPanelCloseButton")
    close:SetPoint("TOPRIGHT", -4, -4)
    close:SetScript("OnClick", function() panel:Hide() end)
    local help = Text("每行一个接收格式，最多 20 条；文字、空格需与实际通报一致。\n%name 提取名称；%mark 提取标记；各最多 1 处，至少一种。\n%text 匹配非空文字（最多 2 处）。\nSeUI 喊话用 %f，这里用 %name；队友设置焦点时即可通报。", 22, -54, "GameFontDisableSmall")
    help:SetWidth(578)
    help:SetHeight(60)
    help:SetWordWrap(true)
    local surround = CreateFrame("Frame", nil, panel, "BackdropTemplate")
    surround:SetPoint("TOPLEFT", 20, -125)
    surround:SetSize(580, 222)
    surround:SetBackdrop({ bgFile = "Interface\\Buttons\\WHITE8X8", edgeFile = "Interface\\Buttons\\WHITE8X8", edgeSize = 1 })
    surround:SetBackdropColor(0.01, 0.02, 0.03, 1)
    surround:SetBackdropBorderColor(0.2, 0.4, 0.42, 1)
    local scroll = CreateFrame("ScrollFrame", nil, panel, "UIPanelScrollFrameTemplate")
    scroll:SetPoint("TOPLEFT", 26, -131)
    scroll:SetSize(548, 210)
    local status
    local formats = CreateFrame("EditBox", "PartyTargetWatchFormatsInput", scroll)
    formats:SetMultiLine(true)
    formats:SetAutoFocus(false)
    formats:SetFontObject("ChatFontNormal")
    formats:SetSize(540, 1)
    formats:SetPoint("TOPLEFT", 0, 0)
    formats:SetMaxLetters(16384)
    formats:SetMaxBytes(16384)
    formats:SetAltArrowKeyMode(false)
    formats:SetTextInsets(4, 4, 4, 4)
    formats:SetScript("OnEscapePressed", formats.ClearFocus)
    scroll:SetScrollChild(formats)
    scroll:EnableMouse(true)
    scroll:SetScript("OnMouseDown", function() formats:SetFocus() end)
    ScrollingEdit_OnLoad(formats)
    formats:SetScript("OnCursorChanged", ScrollingEdit_OnCursorChanged)
    formats:SetScript("OnTextChanged", function(self)
        ScrollingEdit_OnTextChanged(self, scroll)
        if status then status:SetText("草稿已修改；保存后生效，也可以先测试匹配。") end
    end)
    formats:SetScript("OnUpdate", function(self, elapsed)
        ScrollingEdit_OnUpdate(self, elapsed, scroll)
    end)
    -- EditBox doubles visible pipe characters; keep saved templates literal.
    local function LoadText(edit, raw)
        edit:SetText((raw:gsub("|", "||")))
        edit:SetCursorPosition(0)
    end
    local function ReadText(edit) return (edit:GetText():gsub("||", "|")) end
    Text("测试一条实际通报（仅本地预览，不发送聊天）", 22, -369, "GameFontNormal")
    local sample = CreateFrame("EditBox", "PartyTargetWatchFormatSample", panel, "InputBoxTemplate")
    sample:SetPoint("TOPLEFT", 28, -399)
    sample:SetSize(438, 25)
    sample:SetAutoFocus(false)
    sample:SetMaxLetters(510)
    sample:SetMaxBytes(510)
    sample:SetAltArrowKeyMode(false)
    sample:SetText("PTW焦点：训练假人")
    sample:SetScript("OnEscapePressed", sample.ClearFocus)
    status = Text("", 22, -442, "GameFontHighlight")
    status:SetWidth(576)
    status:SetHeight(64)
    status:SetWordWrap(true)
    panel.status = status
    sample:SetScript("OnTextChanged", function()
        status:SetText("测试消息已修改，请重新点击“测试匹配”。")
    end)
    local function Button(text, x, y, width, callback)
        local button = CreateFrame("Button", nil, panel, "UIPanelButtonTemplate")
        button:SetSize(width, 26)
        button:SetPoint("TOPLEFT", x, y)
        button:SetText(text)
        button:SetScript("OnClick", callback)
        return button
    end
    local markerNames = { "星星", "圆圈", "菱形", "三角", "月亮", "方块", "叉叉", "骷髅" }
    local function Test()
        local marker, line, name = ns.Communication.TestDeclarationMessage(ReadText(sample), ReadText(formats))
        if marker or name then
            local display = name or markerNames[marker]
            if name and marker then display = display .. "（" .. markerNames[marker] .. "）" end
            status:SetText("匹配第 " .. line .. " 条格式 → 声明：" .. display)
        else status:SetText(line or "未匹配任何格式。") end
    end
    Button("测试匹配", 480, -398, 116, Test)
    sample:SetScript("OnEnterPressed", Test)
    Button("保存格式", 22, -529, 116, function()
        local ok, reason = ns.Communication.SetDeclarationFormats(ReadText(formats))
        if not ok then status:SetText(reason or "格式无效；未保存。") return end
        LoadText(formats, ns.Communication.GetDeclarationFormats())
        formats:ClearFocus()
        status:SetText("格式已保存，旧约定已清除。请在设置中开启焦点列和聊天声明记录。")
        app.RefreshTargets()
    end)
    Button("加入名称格式", 148, -529, 130, function()
        local template, draft = "PTW焦点：%name", ReadText(formats)
        local found = false
        for line in (draft .. "\n"):gmatch("(.-)\n") do
            if line:match("^%s*(.-)%s*$") == template then found = true; break end
        end
        if not found then
            local separator = draft == "" or draft:sub(-1) == "\n"
            LoadText(formats, draft .. (separator and "" or "\n") .. template)
            formats:SetCursorPosition(#formats:GetText())
        end
        sample:SetText("PTW焦点：训练假人")
        status:SetText("名称格式已在草稿中；点击“保存格式”后生效。队友可手动发送 /p PTW焦点：%f。")
    end)
    Button("恢复内置格式", 286, -529, 142, function()
        LoadText(formats, ns.Communication.GetDefaultDeclarationFormats())
        scroll:SetVerticalScroll(0)
        status:SetText("已填入内置格式；点击“保存格式”后生效。")
    end)
    Button("关闭", 480, -529, 116, function() panel:Hide() end)
    panel.LoadSaved = function()
        LoadText(formats, ns.Communication.GetDeclarationFormats())
        scroll:SetVerticalScroll(0)
        status:SetText("修改后点击“保存格式”生效；关闭会丢弃未保存的草稿。")
    end
    panel:SetScript("OnHide", function() formats:ClearFocus() sample:ClearFocus() end)
    return panel
end
