local _, ns = ...

function ns.CreateSettings(app)
    local db = app.db
    local panel = CreateFrame("Frame", "PartyTargetWatchSettings", UIParent, "BackdropTemplate")
    panel:SetSize(540, 470)
    panel:SetPoint("CENTER")
    panel:SetFrameStrata("DIALOG")
    panel:SetClampedToScreen(true)
    panel:EnableMouse(true)
    panel:SetMovable(true)
    panel:RegisterForDrag("LeftButton")
    panel:SetScript("OnDragStart", panel.StartMoving)
    panel:SetScript("OnDragStop", panel.StopMovingOrSizing)
    panel:SetBackdrop({ bgFile = "Interface\\Buttons\\WHITE8X8", edgeFile = "Interface\\Buttons\\WHITE8X8", edgeSize = 1 })
    panel:SetBackdropColor(0.035, 0.055, 0.075, 0.98)
    panel:SetBackdropBorderColor(0.25, 0.7, 0.65, 1)
    UISpecialFrames[#UISpecialFrames + 1] = "PartyTargetWatchSettings"
    local function Text(text, x, y, font)
        local label = app.NewText(panel, font or "GameFontHighlight")
        label:SetPoint("TOPLEFT", x, y)
        label:SetText(text)
        return label
    end
    Text("队友目标 · 设置", 20, -18, "GameFontNormalLarge")
    local close = CreateFrame("Button", nil, panel, "UIPanelCloseButton")
    close:SetPoint("TOPRIGHT", -4, -4)
    close:SetScript("OnClick", function() panel:Hide() end)
    local function Button(text, x, y, width, callback)
        local button = CreateFrame("Button", nil, panel, "UIPanelButtonTemplate")
        button:SetSize(width, 25)
        button:SetPoint("TOPLEFT", x, y)
        button:SetText(text)
        button:SetScript("OnClick", callback)
        return button
    end
    local checks = {}
    local function Check(key, text, x, y)
        local check = CreateFrame("CheckButton", nil, panel, "UICheckButtonTemplate")
        check:SetSize(26, 26)
        check:SetPoint("TOPLEFT", x, y)
        check.Text = check.Text or app.NewText(check, "GameFontHighlight")
        check.Text:ClearAllPoints()
        check.Text:SetPoint("LEFT", check, "RIGHT", 2, 0)
        check.Text:SetText(text)
        check:SetScript("OnClick", function(self)
            local value = not not self:GetChecked()
            db[key] = value
            app.RebuildRoster()
        end)
        checks[key] = check
    end
    Text("显示场景", 22, -54, "GameFontNormal")
    Check("showWorld", "野外", 20, -78)
    Check("showResting", "主城/旅店（休息区）", 258, -78)
    Check("showDungeon", "地下城（含大秘境）", 20, -108)
    Check("showRaid", "团队副本", 258, -108)
    Check("showScenario", "场景战役", 20, -138)
    Check("showBattleground", "战场", 258, -138)
    Check("showArena", "竞技场", 20, -168)
    local scene = Text("", 258, -175, "GameFontDisableSmall")
    scene:SetWidth(260)
    Text("副本类型优先；示例预览忽略场景筛选。", 22, -207, "GameFontDisableSmall")
    local scaleLabel = Text("", 22, -238)
    local scale = CreateFrame("Slider", "PartyTargetWatchScaleSlider", panel)
    scale:SetPoint("TOPLEFT", 24, -265)
    scale:SetSize(226, 16)
    scale:SetOrientation("HORIZONTAL")
    scale:EnableMouse(true)
    scale:SetThumbTexture("Interface\\Buttons\\UI-SliderBar-Button-Horizontal")
    scale:GetThumbTexture():SetSize(24, 24)
    local track = scale:CreateTexture(nil, "BACKGROUND")
    track:SetPoint("LEFT", 0, 0)
    track:SetPoint("RIGHT", 0, 0)
    track:SetHeight(4)
    track:SetColorTexture(0.2, 0.4, 0.42, 1)
    scale:SetMinMaxValues(0.6, 2)
    scale:SetValueStep(0.05)
    scale:SetObeyStepOnDrag(true)
    Text("60%", 22, -287, "GameFontDisableSmall")
    Text("200%", 221, -287, "GameFontDisableSmall")
    local backgroundLabel = Text("", 284, -238)
    local background = CreateFrame("Slider", "PartyTargetWatchBackgroundAlphaSlider", panel)
    background:SetPoint("TOPLEFT", 286, -265)
    background:SetSize(228, 16)
    background:SetOrientation("HORIZONTAL")
    background:EnableMouse(true)
    background:SetThumbTexture("Interface\\Buttons\\UI-SliderBar-Button-Horizontal")
    background:GetThumbTexture():SetSize(24, 24)
    local backgroundTrack = background:CreateTexture(nil, "BACKGROUND")
    backgroundTrack:SetPoint("LEFT", 0, 0)
    backgroundTrack:SetPoint("RIGHT", 0, 0)
    backgroundTrack:SetHeight(4)
    backgroundTrack:SetColorTexture(0.2, 0.4, 0.42, 1)
    background:SetMinMaxValues(0, 1)
    background:SetValueStep(0.01)
    background:SetObeyStepOnDrag(true)
    Text("全透明", 284, -287, "GameFontDisableSmall")
    Text("不透明", 477, -287, "GameFontDisableSmall")
    Text("位置偏移 X / Y", 22, -314)
    local function Input(x)
        local box = CreateFrame("EditBox", nil, panel, "InputBoxTemplate")
        box:SetSize(75, 24)
        box:SetPoint("TOPLEFT", x, -310)
        box:SetAutoFocus(false)
        box:SetMaxLetters(9)
        box:SetScript("OnEscapePressed", box.ClearFocus)
        return box
    end
    local xInput, yInput = Input(145), Input(235)
    local status = Text("正值向右 / 向上；也可以解锁后拖动窗口标题。", 22, -346, "GameFontDisableSmall")
    status:SetWidth(500)
    local function ApplyPosition()
        local x, y = tonumber(xInput:GetText()), tonumber(yInput:GetText())
        if not app.ValidNumber(x, -10000, 10000) or not app.ValidNumber(y, -10000, 10000) then
            status:SetText("请输入 -10000 到 10000 之间的位置数值。") return
        end
        db.x, db.y = x, y
        app.RestorePosition()
        xInput:ClearFocus() yInput:ClearFocus()
        status:SetText("位置已保存。")
    end
    Button("应用位置", 333, -310, 92, ApplyPosition)
    xInput:SetScript("OnEnterPressed", ApplyPosition)
    yInput:SetScript("OnEnterPressed", ApplyPosition)
    local visibility = Button("", 22, -376, 154, function() db.hidden = not db.hidden app.RebuildRoster() end)
    local lock = Button("", 193, -376, 154, function()
        app.SavePosition() db.locked = not db.locked app.RebuildRoster()
    end)
    local test = Button("", 364, -376, 154, app.TogglePreview)
    Button("窗口居中", 22, -425, 154, function()
        db.point, db.relativePoint, db.x, db.y = "CENTER", "CENTER", 0, 0
        db.hidden = false app.RestorePosition() app.RebuildRoster()
    end)
    Button("恢复默认", 193, -425, 154, app.Reset)
    Button("完成", 364, -425, 154, function() panel:Hide() end)
    local syncing = false
    panel.Sync = function()
        if not panel:IsShown() then return end
        syncing = true
        for key, check in pairs(checks) do check:SetChecked(db[key]) end
        scale:SetValue(db.scale)
        background:SetValue(db.backgroundAlpha)
        scaleLabel:SetText("整体大小：" .. math.floor(db.scale * 100 + 0.5) .. "%")
        backgroundLabel:SetText("背景不透明度：" .. math.floor(db.backgroundAlpha * 100 + 0.5) .. "%")
        xInput:SetText(string.format("%.1f", db.x))
        yInput:SetText(string.format("%.1f", db.y))
        scene:SetText("当前：" .. (app.sceneLabel or "野外"))
        visibility:SetText(db.hidden and "显示监控窗口" or "隐藏监控窗口")
        lock:SetText(db.locked and "解锁位置" or "锁定位置")
        test:SetText(app.preview and "结束示例预览" or "显示示例预览")
        syncing = false
    end
    scale:SetScript("OnValueChanged", function(_, value)
        if syncing or not app.ValidNumber(value, 0.6, 2) then return end
        db.scale = math.floor(value * 100 + 0.5) / 100
        app.RestorePosition()
        scaleLabel:SetText("整体大小：" .. math.floor(db.scale * 100 + 0.5) .. "%")
    end)
    background:SetScript("OnValueChanged", function(_, value)
        if syncing or not app.ValidNumber(value, 0, 1) then return end
        db.backgroundAlpha = math.floor(value * 100 + 0.5) / 100
        app.ApplyAppearance()
        backgroundLabel:SetText("背景不透明度：" .. math.floor(db.backgroundAlpha * 100 + 0.5) .. "%")
    end)
    panel:SetScript("OnShow", panel.Sync)
    return panel
end
